name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Create environment variables file
      run: cp contrib/env-sample .env

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pipenv"
        cache-dependency-path: |
          /home/runner/work/pyquiz/pyquiz/Pipfile.lock

    - name: Cache folder path
      run: mkdir -p /home/runner/.local/share/virtualenvs

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv sync --dev

    - name: Run linter
      run: |
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --exit-zero --max-complexity=10 --statistics

    - name: Run Tests
      run: |
        pipenv run pytest --cov=./quiz --cov-report=xml

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
